((if) @indent.begin)
((switch) @indent.begin)
((case) @indent.begin)
((default) @indent.begin)
((list) @indent.begin)
((macro) @indent.begin)
((function) @indent.begin)
((attempt) @indent.begin)
((user_defined) @indent.begin)
((escape) @indent.begin)

((elseif) @indent.begin)
((recover) @indent.begin)

((closing_tag) @indent.end)
((if) @indent.end)
((switch) @indent.end)
((list) @indent.end)
((macro) @indent.end)
((function) @indent.end)
((attempt) @indent.end)
((escape) @indent.end)

((assign) @indent.ignore)
((import) @indent.ignore)
((include) @indent.ignore)
((stop) @indent.ignore)
((flush) @indent.ignore)
((t) @indent.ignore)